### PR TITLE
Art assets + probuilder installed

### PR DESCRIPTION
**Pull request by psutarjo**

### CODE REVIEW

**Review by aaisara12 — DISMISSED** [review]

**Review by aaisara12 — CHANGES_REQUESTED** [review]
For some reason the mesh renderer for the ground is a bit confused. Maybe it has something to do with that "LightMap Static" checkbox?
Screenshot 2022-02-04 095310

**Comment by psutarjo** [comment]
I'm not having that issue

**Comment by psutarjo** [comment]
Try going to Window -> Package Manager -> ProBuilder -> Samples -> "Import Universal Render Pipeline Support"

**Review by aaisara12 — APPROVED** [review]

**Comment by aaisara12** [comment]
Yep that worked! Is there any way to get that to be imported by default so everyone else who pulls can get it looking right immediately?

**Pull request merged**
